fork = false
# "full", "none"
frame = "none"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
neovim-bin = "/usr/bin/nvim"
no-multigrid = false
srgb = false
tabs = false
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
# Will use the bundled Fira Code Nerd Font by default
normal = ["FiraCode Nerd Font Mono"]
size = 14.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
# Thin and thick values respectively, for all sizes
default = [2, 4]
